import os
OUTDIR = os.path.dirname(os.path.abspath(__file__))

products = [
    {"file":"product-ecodrair.html","name":"Ecodrair Series","cat":"Compressed Air Treatment","badge":"","desc":"Tube-in-tube refrigerant compressed air dryers. 5-180 CFM, 4-16 bar g.","paras":["One of the classic product ranges from SANPAR. The Ecodrair series employs tube-in-tube design of air-to-air and evaporator. The dryer incorporates a hot gas bypass valve for modulating capacity during air flow fluctuations.","The digital dew point indicator ensures high accuracy. These compact dryers have a minimal footprint with rear inlet and outlet connections for easy installation. Designed for silent, reliable operation with minimal maintenance."],"specs":[("Capacity","5 to 180 CFM"),("Operating Pressure","4-16 bar g (up to 50 bar g)"),("Pressure Dew Point","+3 deg C"),("Refrigerant","R134 (eco-friendly)"),("Standard","ISO 8573.1 Class 1.4.1")],"img":"images/products/CAT_D1-5A-cutout-1024x720.webp","features":["Classic tube-in-tube heat exchanger","Hermetically sealed compressor","Modulating capacity controller","Eco-friendly refrigerant R134","Air-cooled condensers up to 50 deg C ambient","Integrated pre-filter and after-filter"]},
    {"file":"product-adsorption.html","name":"Adsorption Dryers","cat":"Compressed Air Treatment","badge":"","desc":"Desiccant-based drying down to -70 deg C dew point. Heatless, HOC, blower, no-purge-loss variants.","paras":["SANPAR has expertise and proven track record to design dryers supplying clean dry air using adsorption techniques. Twin-tower reversible process - moisture is adsorbed during drying and desorbed during regeneration.","The heart consists of desiccants (molecular sieves, activated alumina, silica gel), pressure vessels, directional valves, and control logic. Low pressure drop and low purge loss is the hallmark of SANPAR dryers."],"specs":[("Pressure Dew Point","Down to -70 deg C"),("Operating Pressure","> 7 bar g"),("Types","Heatless, HOC, Blower, No-Purge-Loss"),("Desiccants","Molecular Sieves, Activated Alumina, Silica Gel")],"img":"images/products/Product-6-1024x720.webp","features":["Twin-tower reversible process","Multiple desiccant options","Down to -70 deg C dew point","Low pressure drop design","Four dryer variants available","Custom designed per application"]},
    {"file":"product-filters.html","name":"Compressed Air Filters","cat":"Compressed Air Treatment","badge":"ISO 8573.1 Class 1","desc":"Microfilters for solid, liquid, aerosol, mist and gas removal. Five series from 25 um to 0.01 um.","paras":["SANPAR is one of the leading organisations manufacturing microfilters for critical applications including painting, instrumentation, pneumatics, and textiles.","The design philosophy is low flow, long life rather than high flow, short life - in accordance with energy conservation in compressed air treatment. Cylindrical elements housed in aluminium die-cast or carbon steel housings."],"specs":[("PPF - Primary Pre Filter","SS 316 mesh, up to 25 um"),("PF - Pre Filter","Cellulose acetate, up to 3 um"),("AF - After Filter","Borosilicate glass fibre, 0.1 um"),("FF - Final Filter","Borosilicate glass fibre, 0.01 um"),("AC - Activated Carbon","Oil vapour to 0.003 mg/m3"),("Standard","ISO 8573.1 Class 1")],"img":"images/products/Elements_PFFFCF_1-r9r150tzg7aedje8aem3625p0daamrixg7v5ysqlzs.webp","features":["Five filter series (PPF/PF/AF/FF/AC)","ISO 8573.1 Class 1 compliance","Aluminium or carbon steel housings","Differential pressure gauge included","Zero-loss drain options","Low flow, long life philosophy"]},
    {"file":"product-aftercooler.html","name":"Aftercooler","cat":"Compressed Air Treatment","badge":"ASME Section VIII","desc":"Air-cooled and water-cooled aftercoolers. Copper tubes, SS 316 baffles. ASME compliant.","paras":["Compressed air from compressors is hot with large quantities of water vapour. If not removed, it condenses in distribution causing expensive damage to equipment and processes.","Without an aftercooler, a 200 SCFM compressor at 7 bar introduces 170-240 litres of water daily. SANPAR water-cooled aftercoolers are custom made with complete design flexibility."],"specs":[("Operating Pressure","> 7 bar g"),("Outlet Air Temp","10 deg C above ambient"),("Air Inlet Temp","120 deg C"),("Design Compliance","ASME Section VIII - Div 1"),("Pressure Drop","< 0.1 bar")],"img":"images/products/SAC_WC_1-768x540.webp","features":["Highest quality copper tubes","Removable tube bundle","SS 316 baffle plates","Air-cooled and water-cooled variants","Silver brazing for conductivity","ASME Section VIII compliant"]},
    {"file":"product-separator.html","name":"Moisture Separator","cat":"Compressed Air Treatment","badge":"","desc":"Zero-maintenance centrifugal separator. No moving parts, 0.06 bar constant pressure drop.","paras":["A special design from SANPAR with no moving parts and no replacements needed. This workhorse equipment requires no attention and is an individual value contributor in compressed air treatment.","At a constant pressure drop of not more than 0.06 bar g, this is the least energy-consuming solution. Available in aluminium die-cast or carbon steel housings."],"specs":[("Pressure Drop","0.06 bar g max"),("Moving Parts","None"),("Maintenance","Zero"),("Housing","Aluminium die-cast or carbon steel")],"img":"images/products/MS_1-r9r15b67s5fu8ulyht97upbfr2pnpsb4bzyjh4eq3k.webp","features":["No moving parts","Zero maintenance required","Constant 0.06 bar pressure drop","Compact footprint","10+ standard models","Aluminium or steel housing"]},
    {"file":"product-drains.html","name":"Drains","cat":"Compressed Air Treatment","badge":"","desc":"Condensate drain valves - float, timer, mechanical, and level-sensor types. Max 16 bar g.","paras":["When condensate is not drained, it damages downstream components. Drain valves remove condensate and protect the compressed air treatment system.","SANPAR offers four drain types to suit different operational requirements and budgets, from simple float drains to advanced level-sensor controlled systems."],"specs":[("Internal Drain","Float type, no air loss, 1/2 inch BSP"),("Timer Controlled","Solenoid 230V AC, 1/2 inch BSP"),("Mechanical Float","No electrical supply, zero air loss"),("Level Control","Sensor + solenoid, max 16 bar g")],"img":"images/products/SFD320_1-r9r15r5jg1lg11ln26jap1az5m1r4djmmt8gvpnj4w.webp","features":["Four drain types available","Zero air loss options","No electrical supply option","Max working pressure 16 bar g","Aluminium die-cast housing","1/2 and 3/4 inch BSP connections"]},
    {"file":"product-water-chillers.html","name":"Water Chillers","cat":"Industrial Cooling System","badge":"","desc":"CFC-free process chillers, 0.5TR to 100TR. PLC/microprocessor controlled, 24/7 operation.","paras":["SANPAR water chillers are designed with the user in mind, built to the quality standards that have established SANPAR as a premier process chiller manufacturer.","Complete range of CFC-free chillers from 0.5TR to 100TR in air-cooled and water-cooled versions with advanced heat exchanger design and auto-adaptive control."],"specs":[("Capacity","0.5TR to 100TR"),("Water Outlet Temp","7 deg C"),("Water Inlet Temp","12 deg C"),("Max Ambient","50 deg C"),("Refrigerant","CFC-free"),("Control","PLC / Microprocessor")],"img":"images/products/Water-chiller.webp","features":["0.5TR to 100TR capacity","CFC-free refrigerants","PLC/microprocessor controllers","SS energy-efficient pumps","LAN connectivity","24/7/365 constant temperature"]},
    {"file":"product-air-chillers.html","name":"Air Chillers","cat":"Industrial Cooling System","badge":"","desc":"Closed-circuit refrigeration air chillers. 5 CFM to 10,000 CFM at variable pressures.","paras":["Chillers supply water at constant temperature even with differing ambient conditions and load requests, ensuring optimum efficiency in a closed circuit that reutilises water.","SANPAR air chillers range from 5 CFM to 10,000 CFM at variable pressures with microprocessor-based control and advanced heat exchanger design."],"specs":[("Capacity","5 to 10,000 CFM"),("Pressure","Variable"),("Control","Microprocessor-based"),("Condenser","Air/water cooled")],"img":"images/products/Product-2-768x540.webp","features":["5 to 10,000 CFM capacity","Closed-circuit water reutilisation","Energy-efficient blowers","Microprocessor control with LAN","Auto-adaptive control system","Plate or shell and tube evaporators"]},
    {"file":"product-coolant-chillers.html","name":"Coolant Chillers","cat":"Industrial Cooling System","badge":"","desc":"CFC-free process cooling for machine tools and manufacturing applications.","paras":["SANPAR coolant chillers are designed for unique requirements of process cooling, built to the same quality standards as all SANPAR products.","Custom designed per application with CFC-free refrigerants for environmentally responsible industrial cooling."],"specs":[("Refrigerant","CFC-free"),("Application","Process cooling, machine tools"),("Design","Custom per application")],"img":"images/products/Coolant-r7tjpt18f39ncz2v6qca7bxqwgmxkljyz1x9lqko80.webp","features":["CFC-free refrigerants","Custom per application","Energy-efficient operation","Process cooling optimised"]},
    {"file":"product-dehumidifier.html","name":"Dehumidifier - Xerion Series","cat":"Industrial Air Conditioning","badge":"","desc":"Industrial dehumidifiers. Plus/minus 5% RH, 24/7/365 continuous operation.","paras":["Compact electronic controls, drives, servos and PLCs are extremely sensitive to heat and contamination. Smaller cabinets make temperature control difficult.","The Xerion series works on the condensation principle. A fan draws humid air through an evaporator coil, cooling below dew point. Fully automatic with built-in hygrostat."],"specs":[("RH Accuracy","Plus/minus 5%"),("Operating Humidity","40 to 100%"),("Operating Temperature","15 to 40 deg C"),("Operation","24/7/365"),("Fan Compliance","ErP 2015 norms")],"img":"images/products/SMPL_IAC_PAC.webp","features":["Plus/minus 5% relative humidity","24/7/365 continuous operation","Hermetically sealed compressor","Fully automatic with hygrostat","ErP 2015 compliant fans","CRCA sheet cabinet with wheels"]},
    {"file":"product-precision-ac.html","name":"Precision Air Conditioner","cat":"Industrial Air Conditioning","badge":"","desc":"Climate controller: plus/minus 1 deg C temperature, plus/minus 2% RH. LAN connectivity.","paras":["The SANPAR Precision Air Conditioner precisely controls temperature and humidity with advanced components working in seamless harmony.","Maintains tolerance of plus/minus 1 deg C in temperature and plus/minus 2% in relative humidity. For server rooms, labs, and sensitive electronics requiring 20-25 deg C at 40-55% RH year-round."],"specs":[("Temperature Tolerance","Plus/minus 1 deg C"),("RH Tolerance","Plus/minus 2%"),("Target Environment","20-25 deg C, 40-55% RH"),("Control Cycles","Cooling, Heating, De-Humidification, Humidification"),("Fans","EC variable speed"),("Connectivity","LAN")],"img":"images/products/SMPL_IAC_PAC.webp","features":["Plus/minus 1 deg C accuracy","Plus/minus 2% RH accuracy","Four control cycles","EC variable speed fans","Hot gas reheat for efficiency","LAN connectivity"]},
    {"file":"product-cat-m1.html","name":"CAT M1 Series","cat":"Medical Desiccant Air Dryer","badge":"ISO 8573.1 Class 1","desc":"Medical air filters. 0.01 um particle, 0.003 mg/m3 oil. 5-500 CFM.","paras":["CAT M1 series filters reduce particle size to 0.01 micron and oil concentration to 0.003 mg/m3, delivering ISO 8573.1 Class 1 air quality.","Borosilicate glass fibre and activated carbon filter media in aluminium alloy housing. Maximum operating pressure 16 bar g. For ventilators and medical equipment."],"specs":[("Particle Filtration","0.01 um"),("Oil Concentration","0.003 mg/m3"),("Capacity","5 to 500 CFM"),("Max Pressure","16 bar g"),("Housing","Aluminium alloy"),("Standard","ISO 8573.1 Class 1")],"img":"images/products/FilterSFD_1-r9r9re5ksbgukptzzivzkeebu1vlqxsg7drn44jrfk.webp","features":["ISO 8573.1 Class 1","Borosilicate glass fibre + activated carbon","Medical-grade air purification","For ventilators and medical equipment","Oxygen and nitrogen purification","5 to 500 CFM capacity"]},
    {"file":"product-cat-dth.html","name":"CAT DTH Series","cat":"Medical Desiccant Air Dryer","badge":"BS EN12021:2014","desc":"Medical air dryers for breathing air. -40 deg C dew point. 5-1500 CFM.","paras":["The DTH series uses four variants of adsorption technology to optimise molecular sieve capabilities for removing moisture from medical air, conforming to BS EN12021:2014 breathing air quality.","Removes moisture to eliminate microbial growth. For ventilators and administering anaesthetics. Achieves -40 deg C pressure dew point and lower."],"specs":[("Pressure Dew Point","-40 deg C and lower"),("Capacity","5 to 1500 CFM"),("Standard","BS EN12021:2014, ISO 8573.1 Class 1.2.1"),("Technology","Four adsorption variants"),("Integration","Industry 4.0 remote monitoring")],"img":"images/products/CAT-X1-157A-r9r1p9az9aamxr9q641lxm4awfwxu9z4bck6deqg0w.webp","features":["BS EN12021:2014 breathing air","ISO 8573.1 Class 1.2.1","Four adsorption technologies","-40 deg C dew point","Industry 4.0 remote monitoring","5 to 1500 CFM capacity"]},
]

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="SANPAR {name} - {desc}">
  <title>{name} - SANPAR Industries</title>
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Plus+Jakarta+Sans:wght@600;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="css/tokens.css"><link rel="stylesheet" href="css/layout.css"><link rel="stylesheet" href="css/components.css">
</head>
<body>
<a href="#main-content" class="skip-link">Skip to main content</a>
<header class="header" role="banner"><div class="header__inner"><a href="index.html" class="header__logo"><img src="images/logo/cropped-sanpar-icon-300x300.png" alt="SANPAR" width="36" height="36"> SANPAR</a><nav class="header__nav" aria-label="Main navigation"><ul class="header__menu"><li><a href="index.html">Home</a></li><li><a href="who-we-are.html">About Us</a></li><li><a href="products.html" class="active">Products</a></li><li><a href="industries.html">Industries</a></li><li><a href="support.html">Support</a></li></ul></nav><div class="header__actions"><a href="contact.html" class="btn btn--primary header__cta">Contact Us</a><button class="header__hamburger" aria-label="Open menu"><span></span><span></span><span></span></button></div></div></header>
<div class="mobile-overlay"></div>
<nav class="mobile-nav" aria-label="Mobile navigation"><div class="mobile-nav__header"><span class="header__logo" style="font-size:var(--text-lg)">SANPAR</span><button class="mobile-nav__close" aria-label="Close menu">&times;</button></div><ul class="mobile-nav__menu"><li><a href="index.html">Home</a></li><li><a href="who-we-are.html">About Us</a></li><li><a href="products.html">Products</a></li><li><a href="industries.html">Industries</a></li><li><a href="support.html">Support</a></li></ul><div class="mobile-nav__footer"><a href="contact.html" class="btn btn--primary" style="width:100%;justify-content:center">Contact Us</a></div></nav>
<main id="main-content">
  <nav class="breadcrumb"><ul class="breadcrumb__list"><li><a href="index.html">Home</a></li><li class="breadcrumb__sep">&rsaquo;</li><li><a href="products.html">Products</a></li><li class="breadcrumb__sep">&rsaquo;</li><li class="breadcrumb__current" aria-current="page">{name}</li></ul></nav>
  <section class="section" style="padding-top:var(--space-8)">
    <div class="container">
      <div class="grid grid--2" style="gap:var(--space-12);align-items:center">
        <div class="animate-on-scroll">
          <span class="badge badge--industry" style="margin-bottom:var(--space-4)">{cat}</span>
          {badge_html}<h1 style="font-size:var(--text-7xl)">{name}</h1>
          <p style="color:var(--text-secondary);font-size:var(--text-xl);max-width:48ch">{desc}</p>
          {specs_highlight}
          <div class="flex gap-4" style="flex-wrap:wrap;margin-top:var(--space-6)">
            <a href="contact.html" class="btn btn--primary btn--lg">Request a Quote</a>
            <a href="#specs" class="btn btn--secondary">View Specifications</a>
          </div>
        </div>
        <div class="animate-on-scroll" style="background:var(--grey-1);border-radius:var(--radius-lg);padding:var(--space-8);text-align:center">
          <img src="{img}" alt="SANPAR {name}" style="width:100%;max-height:420px;object-fit:contain" loading="lazy">
        </div>
      </div>
    </div>
  </section>
  <section class="section section--light">
    <div class="container container--narrow"><div class="animate-on-scroll"><h2>Overview</h2>{paras_html}</div></div>
  </section>
  <section class="section">
    <div class="container">
      <div class="text-center animate-on-scroll" style="margin-bottom:var(--space-10)"><span class="label">Key Features</span><h2>Salient Features</h2></div>
      <div class="grid grid--3">{features_html}</div>
    </div>
  </section>
  <section class="section section--light" id="specs">
    <div class="container">
      <div class="text-center animate-on-scroll" style="margin-bottom:var(--space-10)"><span class="label">Technical Data</span><h2>Specifications</h2></div>
      <div class="spec-table-wrapper animate-on-scroll"><table class="spec-table"><thead><tr><th>Parameter</th><th>Value</th></tr></thead><tbody>{specs_html}</tbody></table></div>
    </div>
  </section>
  <section class="section section--dark" style="text-align:center">
    <div class="container container--narrow animate-on-scroll">
      <h2 style="color:var(--text-inverse)">Need a Custom Configuration?</h2>
      <p style="color:rgba(255,255,255,0.7);margin:0 auto var(--space-8)">Our engineering team can design a system tailored to your specific requirements.</p>
      <a href="contact.html" class="btn btn--light btn--lg">Request a Quote</a>
    </div>
  </section>
</main>
<div class="trust-bar"><div class="trust-bar__inner"><div class="trust-bar__item">&#10003; ISO 9001:2015</div><div class="trust-bar__item">&#10003; AS 9100D</div><div class="trust-bar__item">&#10003; 30+ Years</div><div class="trust-bar__item">&#10003; 3000+ Customers</div></div></div>
<footer class="footer" role="contentinfo"><div class="footer__grid"><div class="footer__col"><h4>SANPAR Industries</h4><p>Precision-engineered solutions since 1994.</p></div><div class="footer__col"><h4>Products</h4><ul class="footer__links"><li><a href="products.html">All Products</a></li></ul></div><div class="footer__col"><h4>Company</h4><ul class="footer__links"><li><a href="who-we-are.html">About Us</a></li><li><a href="support.html">Support</a></li></ul></div><div class="footer__col"><h4>Contact</h4><ul class="footer__links"><li><a href="tel:+917349142424">+91 7349 142 424</a></li><li><a href="mailto:enquiry@sanpar.com">enquiry@sanpar.com</a></li></ul></div></div><div class="footer__bottom"><span>&copy; 2025 SANPAR Industries Pvt. Ltd.</span><div class="flex gap-4"><a href="#">Privacy</a><a href="#">Terms</a></div></div></footer>
<script src="js/main.js"></script>
</body>
</html>"""

for p in products:
    badge_html = '<span class="badge badge--cert" style="margin-bottom:var(--space-4)">{}</span>'.format(p["badge"]) if p["badge"] else ""
    paras_html = "".join("<p>{}</p>".format(para) for para in p["paras"])
    features_html = "".join('<div class="animate-on-scroll" style="padding:var(--space-6);background:var(--bg-light);border-radius:var(--radius-md)"><h4>{}</h4></div>'.format(f) for f in p["features"])
    specs_html = "".join("<tr><td>{}</td><td>{}</td></tr>".format(s[0], s[1]) for s in p["specs"])
    first3 = p["specs"][:3]
    specs_highlight = '<div style="display:flex;gap:var(--space-6);margin:var(--space-6) 0;flex-wrap:wrap">' + "".join('<div><strong style="font-family:var(--font-display);font-size:var(--text-xl);color:var(--color-primary)">{}</strong><br><span style="font-size:var(--text-sm);color:var(--text-tertiary)">{}</span></div>'.format(s[1],s[0]) for s in first3) + '</div>'

    html = TEMPLATE.format(name=p["name"],cat=p["cat"],desc=p["desc"],img=p["img"],badge_html=badge_html,paras_html=paras_html,features_html=features_html,specs_html=specs_html,specs_highlight=specs_highlight)
    filepath = os.path.join(OUTDIR, p["file"])
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)
    print("Created " + p["file"])

print("\nDone: {} product pages created".format(len(products)))
