export interface Insight {
  slug: string
  title: string
  category: string
  readTime: string
  excerpt: string
  image: string
  featured?: boolean
  body: string[]
}

export const insights: Insight[] = [
  {
    slug: 'hidden-cost-wet-compressed-air',
    title: 'The Hidden Cost of Wet Compressed Air in Pharmaceutical Manufacturing',
    category: 'Compressed Air',
    readTime: '5 min',
    excerpt: 'Moisture in compressed air costs pharmaceutical plants more than they realise — in batch failures, contamination risk, and regulatory exposure.',
    image: '/images/blog/pharma-compressed-air.png',
    featured: true,
    body: [
      'Compressed air is often called the "fourth utility" in pharmaceutical manufacturing — after electricity, water, and gas. Yet unlike those utilities, compressed air quality is frequently overlooked until something goes wrong. And in pharma, when something goes wrong with air quality, the consequences are severe: batch contamination, regulatory non-compliance, product recalls, and significant financial losses.',
      'The core issue is moisture. Every compressor draws in ambient air containing water vapour. When that air is compressed, the relative humidity increases dramatically, often reaching saturation. Without proper treatment, this moisture travels through the air distribution system and into critical processes — cleanroom environments, tablet coating, sterile fill-finish lines, and pneumatic instrumentation.',
      'The financial impact is rarely calculated holistically. Plant engineers see the cost of a dryer and weigh it against their capital budget. What they don\'t see is the cumulative cost of moisture-related failures: rejected batches worth lakhs, unplanned maintenance on pneumatic valves corroded by wet air, and the invisible cost of operating in a state of regulatory risk.',
      'SANPAR\'s approach to pharmaceutical compressed air treatment combines ECODRAIR refrigeration dryers for standard applications with adsorption dryers for ultra-dry requirements (-40°C to -70°C dew point). Paired with 5-stage filtration, this ensures pharmaceutical-grade air quality at every point of use.',
      'The key insight for plant engineers: the cost of proper compressed air treatment is always less than the cost of a single contaminated batch. Invest in the right dryer specification upfront, validate the system annually, and monitor dew point continuously. Your compressed air system is a production-critical utility — treat it like one.',
    ],
  },
  {
    slug: 'why-your-chiller-is-undersized',
    title: 'Why Your Industrial Chiller Is Probably Undersized',
    category: 'Industrial Cooling',
    readTime: '4 min',
    excerpt: 'Most plant engineers specify chillers at nominal load. Here is why that calculation is almost always wrong — and how to fix it.',
    image: '/images/blog/chiller-undersized.webp',
    body: [
      'Industrial chillers are specified based on cooling load calculations. In theory, this is straightforward: determine the heat generated by the process, add safety margins, and select a chiller with matching capacity. In practice, most chillers are undersized — not because engineers make arithmetic errors, but because the inputs to those calculations are systematically wrong.',
      'The most common mistake is specifying at nominal load rather than peak load. A CNC machine tool\'s spindle generates a certain amount of heat during normal cutting operations. But during heavy roughing passes, tool changes with rapid acceleration, or extended operation in high ambient temperatures, the heat load can spike to 150-200% of nominal. If the chiller is sized for nominal, it cannot maintain temperature during these peaks.',
      'The second common error is ignoring ambient temperature variation. A chiller specified to deliver 20°C coolant when ambient is 25°C will struggle to maintain that setpoint when ambient reaches 40°C — which happens routinely in Indian summers. The chiller\'s effective capacity drops as the temperature differential between coolant and ambient narrows.',
      'SANPAR\'s approach to chiller specification starts with a thorough application audit. We measure actual heat loads across operating conditions, factor in ambient extremes for the installation site, and apply appropriate safety margins. Our water chillers, coolant chillers, and oil chillers are available from 1 TR to 30 TR with ±0.5°C temperature control accuracy.',
      'The recommendation: always specify your chiller at peak load plus a 20% safety margin, calculated at your site\'s maximum ambient temperature. The marginal cost of a slightly larger chiller is trivial compared to the production losses from a chiller that cannot keep up during peak demand.',
    ],
  },
  {
    slug: 'sanpar-hannover-messe-2015',
    title: 'SANPAR at HANNOVER MESSE 2015 — Taking Indian Thermal Engineering Global',
    category: 'Industry News',
    readTime: '3 min',
    excerpt: 'In 2015, SANPAR took the stage at the world\'s largest industrial trade fair. Here is what we learned — and what it meant for Indian manufacturing.',
    image: '/images/blog/hannover-messe.webp',
    body: [
      'In April 2015, SANPAR Industries participated in HANNOVER MESSE — the world\'s largest industrial technology trade fair, held annually in Hannover, Germany. For a Bengaluru-based thermal engineering company, this was more than an exhibition; it was a statement of intent to compete on a global stage.',
      'The exhibition provided three critical insights. First, the global market for compressed air treatment and industrial cooling is significantly larger than most Indian manufacturers realise. European and American manufacturers dominate not because of superior technology, but because of superior branding, documentation, and digital presence.',
      'Second, Indian thermal engineering has a genuine competitive advantage in price-performance ratio. SANPAR\'s ECODRAIR and XEROS series products matched the performance specifications of European competitors at a fraction of the cost. International buyers were genuinely interested — but they needed to see world-class packaging: professional datasheets, certifiable quality documentation, and a website that communicated credibility.',
      'Third, the defence and aerospace thermal management segment is where India has the most compelling differentiation story. SANPAR\'s DGAQA and CEMILAC certifications — achieved through years of rigorous qualification — are rare credentials that very few Indian manufacturers possess. This positions SANPAR uniquely for international defence procurement programmes seeking certified Indian suppliers.',
      'HANNOVER MESSE 2015 marked a turning point in SANPAR\'s strategy: from a domestic manufacturer to a company with global ambitions backed by world-class certifications and proven technology.',
    ],
  },
  {
    slug: 'dgaqa-cemilac-certification-journey',
    title: 'The Road to DGAQA and CEMILAC Certification',
    category: 'Defence Technology',
    readTime: '6 min',
    excerpt: 'Achieving defence-grade certification for airborne thermal systems is not a checkbox exercise. It is a multi-year engineering commitment.',
    image: '/images/blog/dgaqa-certification.gif',
    body: [
      'When a thermal management system is installed in an aircraft — whether for radar cooling, avionics thermal management, or environmental control — it must meet standards that are orders of magnitude beyond commercial requirements. It must function in extreme vibration, temperature ranges from -40°C to +70°C, altitude depressurisation, and electromagnetic interference environments. Failure is not an option when the system is 30,000 feet in the air.',
      'DGAQA (Directorate General of Aeronautical Quality Assurance) and CEMILAC (Centre for Military Airworthiness and Certification) are India\'s apex bodies for military aviation quality and airworthiness certification. Obtaining their approval for an airborne thermal system is a multi-year process involving design review, prototype testing, environmental qualification testing, production process validation, and sustained production audits.',
      'SANPAR\'s journey to DGAQA and CEMILAC certification for our Airborne Liquid Cooling System (LCS) began in 2010 with ground testing of liquid cooling systems for defence applications. The initial system proved the core technology — precision temperature control of EGW (Ethylene Glycol Water) coolant for radar electronics. But airborne qualification required a fundamentally different engineering approach: every component had to meet military specifications for weight, vibration resistance, altitude performance, and electromagnetic compatibility.',
      'The qualification testing phase alone took over two years. The system was subjected to MIL-STD environmental tests: temperature cycling, humidity, vibration (random and sinusoidal), altitude simulation, EMI/EMC, and salt fog corrosion. Each test required meticulous documentation, and any failure required root cause analysis, design modification, and re-testing from scratch.',
      'In 2016, the Airborne LCS received both DGAQA and CEMILAC approval — making SANPAR one of very few Indian companies qualified to supply airborne thermal management systems for military aviation. This certification has since underpinned our supply to LRDE/DRDO programmes and the establishment of SANPAR Defence Systems Pvt. Ltd. as a dedicated defence entity in 2024.',
      'The lesson from this journey is clear: defence-grade certification is not a marketing badge — it is an engineering commitment that transforms every process in the company, from design methodology to production quality systems to after-sales support. AS 9100 D certification, achieved in 2017, further reinforced this quality culture across all SANPAR operations.',
    ],
  },
]

export function getInsightBySlug(slug: string): Insight | undefined {
  return insights.find((i) => i.slug === slug)
}
