name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 167.71.237.239
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          source: "site-build/*"
          target: "/var/www/sanpar/v3/"
          strip_components: 1

      - name: Set permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 167.71.237.239
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: chmod -R 755 /var/www/sanpar/v3/
